# Generated by Django 5.2.1 on 2026-03-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='accommodation',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='food',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='overall_experience',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='registration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='talks_and_discussions',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='travel',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='venue',
            field=models.IntegerField(default=5),
        ),
    ]
