# Generated by Django 5.2.1 on 2026-03-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_feedback_accommodation_feedback_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='accommodation',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='food',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='overall_experience',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='registration',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='talks_and_discussions',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='travel',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='venue',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
